if SERVER then
	AddCSLuaFile()
end

local GAMETYPE = {}

GAMETYPE.Name = "Half-Life 2: Episode 1"
GAMETYPE.BaseGameType = "hl2"
GAMETYPE.MapScript = {}
GAMETYPE.MapList =
{
	"ep1_citadel_00",
	"ep1_citadel_01",
	"ep1_citadel_02",
	"ep1_citadel_02b",
	"ep1_citadel_03",
	"ep1_citadel_04",
	"ep1_c17_00",
	"ep1_c17_00a",
	"ep1_c17_01",
	"ep1_c17_02",
	"ep1_c17_02b",
	"ep1_c17_02a",
	"ep1_c17_05",
	"ep1_c17_06",
}

GAMETYPE.ClassesEnemyNPC =
{
	["npc_metropolice"] = true,
	["npc_combine"] = true,
	["npc_combine_s"] = true,
	["npc_zombie"] = true,
	["npc_headcrab"] = true,
}

GAMETYPE.ImportantPlayerNPCNames =
{
}

GAMETYPE.ImportantPlayerNPCClasses =
{
	["npc_alyx"] = true,
	["npc_barney"] = true,
	["npc_odessa"] = true,
	["npc_kleiner"] = true,
	["npc_dog"] = true,
	["npc_eli"] = true,
	["npc_mossman"] = true,
}

function GAMETYPE:LoadMapScript()
	local MAPSCRIPT_FILE = "lambda/gamemode/gametypes/hl2ep1/mapscripts/" .. game.GetMap():lower() .. ".lua"
	DbgPrint("Path: " .. MAPSCRIPT_FILE)
	self.MapScript = nil
	if file.Exists(MAPSCRIPT_FILE, "LUA") == true then
		self.MapScript = include(MAPSCRIPT_FILE)
		if self.MapScript ~= nil then
			DbgPrint("Loaded mapscript: " .. MAPSCRIPT_FILE)
		else
			self.MapScript = {}
		end
	else
		DbgPrint("EP1: No mapscript available.")
		self.MapScript = {}
	end
end

function GAMETYPE:LoadGameContent()

	local requiredFiles = {
		{ "models/advisorpod.ani", "episodic" },
		{ "models/advisorpod.dx80.vtx", "episodic" },
		{ "models/advisorpod.dx90.vtx", "episodic" },
		{ "models/advisorpod.mdl", "episodic" },
		{ "models/advisorpod.phy", "episodic" },
		{ "models/advisorpod.sw.vtx", "episodic" },
		{ "models/advisorpod.vvd", "episodic" },
		{ "models/advisorpodskybox.dx80.vtx", "episodic" },
		{ "models/advisorpodskybox.dx90.vtx", "episodic" },
		{ "models/advisorpodskybox.mdl", "episodic" },
		{ "models/advisorpodskybox.sw.vtx", "episodic" },
		{ "models/advisorpodskybox.vvd", "episodic" },
		{ "models/alyx.dx80.vtx", "episodic" },
		{ "models/alyx.dx90.vtx", "episodic" },
		{ "models/alyx.mdl", "episodic" },
		{ "models/alyx.phy", "episodic" },
		{ "models/alyx.sw.vtx", "episodic" },
		{ "models/alyx.vvd", "episodic" },
		{ "models/alyx_animations.ani", "episodic" },
		{ "models/alyx_animations.mdl", "episodic" },
		{ "models/alyx_gestures.ani", "episodic" },
		{ "models/alyx_gestures.mdl", "episodic" },
		{ "models/alyx_intro.dx80.vtx", "episodic" },
		{ "models/alyx_intro.dx90.vtx", "episodic" },
		{ "models/alyx_intro.mdl", "episodic" },
		{ "models/alyx_intro.sw.vtx", "episodic" },
		{ "models/alyx_intro.vvd", "episodic" },
		{ "models/alyx_postures.ani", "episodic" },
		{ "models/alyx_postures.mdl", "episodic" },
		{ "models/antlion.ani", "episodic" },
		{ "models/antlion.dx80.vtx", "episodic" },
		{ "models/antlion.dx90.vtx", "episodic" },
		{ "models/antlion.mdl", "episodic" },
		{ "models/antlion.phy", "episodic" },
		{ "models/antlion.sw.vtx", "episodic" },
		{ "models/antlion.vvd", "episodic" },
		{ "models/antlion_guard.ani", "episodic" },
		{ "models/antlion_guard.dx80.vtx", "episodic" },
		{ "models/antlion_guard.dx90.vtx", "episodic" },
		{ "models/antlion_guard.mdl", "episodic" },
		{ "models/antlion_guard.phy", "episodic" },
		{ "models/antlion_guard.sw.vtx", "episodic" },
		{ "models/antlion_guard.vvd", "episodic" },
		{ "models/barney.dx80.vtx", "episodic" },
		{ "models/barney.dx90.vtx", "episodic" },
		{ "models/barney.mdl", "episodic" },
		{ "models/barney.phy", "episodic" },
		{ "models/barney.sw.vtx", "episodic" },
		{ "models/barney.vvd", "episodic" },
		{ "models/barney_animations.ani", "episodic" },
		{ "models/barney_animations.mdl", "episodic" },
		{ "models/barney_gestures.ani", "episodic" },
		{ "models/barney_gestures.mdl", "episodic" },
		{ "models/barney_postures.ani", "episodic" },
		{ "models/barney_postures.mdl", "episodic" },
		{ "models/blackout.dx80.vtx", "episodic" },
		{ "models/blackout.dx90.vtx", "episodic" },
		{ "models/blackout.mdl", "episodic" },
		{ "models/blackout.phy", "episodic" },
		{ "models/blackout.sw.vtx", "episodic" },
		{ "models/blackout.vvd", "episodic" },
		{ "models/combine_apc_destroyed_gib01.dx80.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib01.dx90.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib01.mdl", "episodic" },
		{ "models/combine_apc_destroyed_gib01.phy", "episodic" },
		{ "models/combine_apc_destroyed_gib01.sw.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib01.vvd", "episodic" },
		{ "models/combine_apc_destroyed_gib02.dx80.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib02.dx90.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib02.mdl", "episodic" },
		{ "models/combine_apc_destroyed_gib02.phy", "episodic" },
		{ "models/combine_apc_destroyed_gib02.sw.vtx", "episodic" },
		{ "models/combine_apc_destroyed_gib02.vvd", "episodic" },
		{ "models/combine_dropship.dx80.vtx", "episodic" },
		{ "models/combine_dropship.dx90.vtx", "episodic" },
		{ "models/combine_dropship.mdl", "episodic" },
		{ "models/combine_dropship.phy", "episodic" },
		{ "models/combine_dropship.sw.vtx", "episodic" },
		{ "models/combine_dropship.vvd", "episodic" },
		{ "models/combine_dropship_animations.ani", "episodic" },
		{ "models/combine_dropship_animations.mdl", "episodic" },
		{ "models/combine_dropship_container_static.dx80.vtx", "episodic" },
		{ "models/combine_dropship_container_static.dx90.vtx", "episodic" },
		{ "models/combine_dropship_container_static.mdl", "episodic" },
		{ "models/combine_dropship_container_static.phy", "episodic" },
		{ "models/combine_dropship_container_static.sw.vtx", "episodic" },
		{ "models/combine_dropship_container_static.vvd", "episodic" },
		{ "models/combine_strider.ani", "episodic" },
		{ "models/combine_strider.dx80.vtx", "episodic" },
		{ "models/combine_strider.dx90.vtx", "episodic" },
		{ "models/combine_strider.mdl", "episodic" },
		{ "models/combine_strider.phy", "episodic" },
		{ "models/combine_strider.sw.vtx", "episodic" },
		{ "models/combine_strider.vvd", "episodic" },
		{ "models/combine_wall.ani", "episodic" },
		{ "models/combine_wall.dx80.vtx", "episodic" },
		{ "models/combine_wall.dx90.vtx", "episodic" },
		{ "models/combine_wall.mdl", "episodic" },
		{ "models/combine_wall.sw.vtx", "episodic" },
		{ "models/combine_wall.vvd", "episodic" },
		{ "models/crashedgunship.dx80.vtx", "episodic" },
		{ "models/crashedgunship.dx90.vtx", "episodic" },
		{ "models/crashedgunship.mdl", "episodic" },
		{ "models/crashedgunship.phy", "episodic" },
		{ "models/crashedgunship.sw.vtx", "episodic" },
		{ "models/crashedgunship.vvd", "episodic" },
		{ "models/dog.dx80.vtx", "episodic" },
		{ "models/dog.dx90.vtx", "episodic" },
		{ "models/dog.mdl", "episodic" },
		{ "models/dog.phy", "episodic" },
		{ "models/dog.sw.vtx", "episodic" },
		{ "models/dog.vvd", "episodic" },
		{ "models/dog_animations.ani", "episodic" },
		{ "models/dog_animations.mdl", "episodic" },
		{ "models/dog_gestures.ani", "episodic" },
		{ "models/dog_gestures.mdl", "episodic" },
		{ "models/dog_postures.ani", "episodic" },
		{ "models/dog_postures.mdl", "episodic" },
		{ "models/eli.dx80.vtx", "episodic" },
		{ "models/eli.dx90.vtx", "episodic" },
		{ "models/eli.mdl", "episodic" },
		{ "models/eli.phy", "episodic" },
		{ "models/eli.sw.vtx", "episodic" },
		{ "models/eli.vvd", "episodic" },
		{ "models/eli_anims.ani", "episodic" },
		{ "models/eli_anims.mdl", "episodic" },
		{ "models/eli_gestures.ani", "episodic" },
		{ "models/eli_gestures.mdl", "episodic" },
		{ "models/eli_monitor.dx80.vtx", "episodic" },
		{ "models/eli_monitor.dx90.vtx", "episodic" },
		{ "models/eli_monitor.mdl", "episodic" },
		{ "models/eli_monitor.phy", "episodic" },
		{ "models/eli_monitor.sw.vtx", "episodic" },
		{ "models/eli_monitor.vvd", "episodic" },
		{ "models/eli_postures.ani", "episodic" },
		{ "models/eli_postures.mdl", "episodic" },
		{ "models/ep1_combine_wall.ani", "episodic" },
		{ "models/ep1_combine_wall.dx80.vtx", "episodic" },
		{ "models/ep1_combine_wall.dx90.vtx", "episodic" },
		{ "models/ep1_combine_wall.mdl", "episodic" },
		{ "models/ep1_combine_wall.phy", "episodic" },
		{ "models/ep1_combine_wall.sw.vtx", "episodic" },
		{ "models/ep1_combine_wall.vvd", "episodic" },
		{ "models/ghostanim.ani", "episodic" },
		{ "models/ghostanim.dx80.vtx", "episodic" },
		{ "models/ghostanim.dx90.vtx", "episodic" },
		{ "models/ghostanim.mdl", "episodic" },
		{ "models/ghostanim.sw.vtx", "episodic" },
		{ "models/ghostanim.vvd", "episodic" },
		{ "models/ghostanim_van.ani", "episodic" },
		{ "models/ghostanim_van.dx80.vtx", "episodic" },
		{ "models/ghostanim_van.dx90.vtx", "episodic" },
		{ "models/ghostanim_van.mdl", "episodic" },
		{ "models/ghostanim_van.phy", "episodic" },
		{ "models/ghostanim_van.sw.vtx", "episodic" },
		{ "models/ghostanim_van.vvd", "episodic" },
		{ "models/gman.dx80.vtx", "episodic" },
		{ "models/gman.dx90.vtx", "episodic" },
		{ "models/gman.mdl", "episodic" },
		{ "models/gman.phy", "episodic" },
		{ "models/gman.sw.vtx", "episodic" },
		{ "models/gman.vvd", "episodic" },
		{ "models/gman_animations.ani", "episodic" },
		{ "models/gman_animations.mdl", "episodic" },
		{ "models/gman_gestures.ani", "episodic" },
		{ "models/gman_gestures.mdl", "episodic" },
		{ "models/gman_postures.ani", "episodic" },
		{ "models/gman_postures.mdl", "episodic" },
		{ "models/headcrab.ani", "episodic" },
		{ "models/headcrab.dx80.vtx", "episodic" },
		{ "models/headcrab.dx90.vtx", "episodic" },
		{ "models/headcrab.mdl", "episodic" },
		{ "models/headcrab.phy", "episodic" },
		{ "models/headcrab.sw.vtx", "episodic" },
		{ "models/headcrab.vvd", "episodic" },
		{ "models/headcrabblack.ani", "episodic" },
		{ "models/headcrabblack.dx80.vtx", "episodic" },
		{ "models/headcrabblack.dx90.vtx", "episodic" },
		{ "models/headcrabblack.mdl", "episodic" },
		{ "models/headcrabblack.phy", "episodic" },
		{ "models/headcrabblack.sw.vtx", "episodic" },
		{ "models/headcrabblack.vvd", "episodic" },
		{ "models/headcrabclassic.ani", "episodic" },
		{ "models/headcrabclassic.dx80.vtx", "episodic" },
		{ "models/headcrabclassic.dx90.vtx", "episodic" },
		{ "models/headcrabclassic.mdl", "episodic" },
		{ "models/headcrabclassic.phy", "episodic" },
		{ "models/headcrabclassic.sw.vtx", "episodic" },
		{ "models/headcrabclassic.vvd", "episodic" },
		{ "models/kleiner.dx80.vtx", "episodic" },
		{ "models/kleiner.dx90.vtx", "episodic" },
		{ "models/kleiner.mdl", "episodic" },
		{ "models/kleiner.phy", "episodic" },
		{ "models/kleiner.sw.vtx", "episodic" },
		{ "models/kleiner.vvd", "episodic" },
		{ "models/kleiner_animations.ani", "episodic" },
		{ "models/kleiner_animations.mdl", "episodic" },
		{ "models/kleiner_gestures.ani", "episodic" },
		{ "models/kleiner_gestures.mdl", "episodic" },
		{ "models/kleiner_monitor.dx80.vtx", "episodic" },
		{ "models/kleiner_monitor.dx90.vtx", "episodic" },
		{ "models/kleiner_monitor.mdl", "episodic" },
		{ "models/kleiner_monitor.phy", "episodic" },
		{ "models/kleiner_monitor.sw.vtx", "episodic" },
		{ "models/kleiner_monitor.vvd", "episodic" },
		{ "models/kleiner_postures.ani", "episodic" },
		{ "models/kleiner_postures.mdl", "episodic" },
		{ "models/ministrider.dx80.vtx", "episodic" },
		{ "models/ministrider.dx90.vtx", "episodic" },
		{ "models/ministrider.mdl", "episodic" },
		{ "models/ministrider.phy", "episodic" },
		{ "models/ministrider.sw.vtx", "episodic" },
		{ "models/ministrider.vvd", "episodic" },
		{ "models/ministrider_animations.ani", "episodic" },
		{ "models/ministrider_animations.mdl", "episodic" },
		{ "models/mossman.dx80.vtx", "episodic" },
		{ "models/mossman.dx90.vtx", "episodic" },
		{ "models/mossman.mdl", "episodic" },
		{ "models/mossman.phy", "episodic" },
		{ "models/mossman.sw.vtx", "episodic" },
		{ "models/mossman.vvd", "episodic" },
		{ "models/mossman_anims.ani", "episodic" },
		{ "models/mossman_anims.mdl", "episodic" },
		{ "models/mossman_gestures.ani", "episodic" },
		{ "models/mossman_gestures.mdl", "episodic" },
		{ "models/mossman_postures.ani", "episodic" },
		{ "models/mossman_postures.mdl", "episodic" },
		{ "models/roller.dx80.vtx", "episodic" },
		{ "models/roller.dx90.vtx", "episodic" },
		{ "models/roller.mdl", "episodic" },
		{ "models/roller.phy", "episodic" },
		{ "models/roller.sw.vtx", "episodic" },
		{ "models/roller.vvd", "episodic" },
		{ "models/roller_spikes.dx80.vtx", "episodic" },
		{ "models/roller_spikes.dx90.vtx", "episodic" },
		{ "models/roller_spikes.mdl", "episodic" },
		{ "models/roller_spikes.phy", "episodic" },
		{ "models/roller_spikes.sw.vtx", "episodic" },
		{ "models/roller_spikes.vvd", "episodic" },
		{ "models/stalker.dx80.vtx", "episodic" },
		{ "models/stalker.dx90.vtx", "episodic" },
		{ "models/stalker.mdl", "episodic" },
		{ "models/stalker.phy", "episodic" },
		{ "models/stalker.sw.vtx", "episodic" },
		{ "models/stalker.vvd", "episodic" },
		{ "models/stalker_animations.ani", "episodic" },
		{ "models/stalker_animations.mdl", "episodic" },
		{ "models/vortigaunt.dx80.vtx", "episodic" },
		{ "models/vortigaunt.dx90.vtx", "episodic" },
		{ "models/vortigaunt.mdl", "episodic" },
		{ "models/vortigaunt.phy", "episodic" },
		{ "models/vortigaunt.sw.vtx", "episodic" },
		{ "models/vortigaunt.vvd", "episodic" },
		{ "models/vortigaunt_anims.ani", "episodic" },
		{ "models/vortigaunt_anims.mdl", "episodic" },
		{ "models/vortigaunt_blue.dx80.vtx", "episodic" },
		{ "models/vortigaunt_blue.dx90.vtx", "episodic" },
		{ "models/vortigaunt_blue.mdl", "episodic" },
		{ "models/vortigaunt_blue.phy", "episodic" },
		{ "models/vortigaunt_blue.sw.vtx", "episodic" },
		{ "models/vortigaunt_blue.vvd", "episodic" },
		{ "models/vortigaunt_gestures.ani", "episodic" },
		{ "models/vortigaunt_gestures.mdl", "episodic" },
		{ "models/vortigaunt_postures.ani", "episodic" },
		{ "models/vortigaunt_postures.mdl", "episodic" },
		{ "models/combine_turrets/ceiling_turret.dx80.vtx", "episodic" },
		{ "models/combine_turrets/ceiling_turret.dx90.vtx", "episodic" },
		{ "models/combine_turrets/ceiling_turret.mdl", "episodic" },
		{ "models/combine_turrets/ceiling_turret.sw.vtx", "episodic" },
		{ "models/combine_turrets/ceiling_turret.vvd", "episodic" },
		{ "models/effects/introtear.dx80.vtx", "episodic" },
		{ "models/effects/introtear.dx90.vtx", "episodic" },
		{ "models/effects/introtear.mdl", "episodic" },
		{ "models/effects/introtear.sw.vtx", "episodic" },
		{ "models/effects/introtear.vvd", "episodic" },
		{ "models/effects/intro_vortshield.dx80.vtx", "episodic" },
		{ "models/effects/intro_vortshield.dx90.vtx", "episodic" },
		{ "models/effects/intro_vortshield.mdl", "episodic" },
		{ "models/effects/intro_vortshield.sw.vtx", "episodic" },
		{ "models/effects/intro_vortshield.vvd", "episodic" },
		{ "models/effects/splode.dx80.vtx", "episodic" },
		{ "models/effects/splode.dx90.vtx", "episodic" },
		{ "models/effects/splode.mdl", "episodic" },
		{ "models/effects/splode.sw.vtx", "episodic" },
		{ "models/effects/splode.vvd", "episodic" },
		{ "models/effects/vol_light02.dx80.vtx", "episodic" },
		{ "models/effects/vol_light02.dx90.vtx", "episodic" },
		{ "models/effects/vol_light02.mdl", "episodic" },
		{ "models/effects/vol_light02.sw.vtx", "episodic" },
		{ "models/effects/vol_light02.vvd", "episodic" },
		{ "models/extras/crank.dx80.vtx", "episodic" },
		{ "models/extras/crank.dx90.vtx", "episodic" },
		{ "models/extras/crank.mdl", "episodic" },
		{ "models/extras/crank.phy", "episodic" },
		{ "models/extras/crank.sw.vtx", "episodic" },
		{ "models/extras/crank.vvd", "episodic" },
		{ "models/extras/widget.dx80.vtx", "episodic" },
		{ "models/extras/widget.dx90.vtx", "episodic" },
		{ "models/extras/widget.mdl", "episodic" },
		{ "models/extras/widget.phy", "episodic" },
		{ "models/extras/widget.sw.vtx", "episodic" },
		{ "models/extras/widget.vvd", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.dx80.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.dx90.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.mdl", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.phy", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.sw.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_01.vvd", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.dx80.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.dx90.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.mdl", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.phy", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.sw.vtx", "episodic" },
		{ "models/gibs/helicopter_brokenpiece_02.vvd", "episodic" },
		{ "models/gibs/metal_gib3.dx80.vtx", "episodic" },
		{ "models/gibs/metal_gib3.dx90.vtx", "episodic" },
		{ "models/gibs/metal_gib3.mdl", "episodic" },
		{ "models/gibs/metal_gib3.phy", "episodic" },
		{ "models/gibs/metal_gib3.sw.vtx", "episodic" },
		{ "models/gibs/metal_gib3.vvd", "episodic" },
		{ "models/gibs/metal_gib4.dx80.vtx", "episodic" },
		{ "models/gibs/metal_gib4.dx90.vtx", "episodic" },
		{ "models/gibs/metal_gib4.mdl", "episodic" },
		{ "models/gibs/metal_gib4.phy", "episodic" },
		{ "models/gibs/metal_gib4.sw.vtx", "episodic" },
		{ "models/gibs/metal_gib4.vvd", "episodic" },
		{ "models/gibs/metal_gib5.dx80.vtx", "episodic" },
		{ "models/gibs/metal_gib5.dx90.vtx", "episodic" },
		{ "models/gibs/metal_gib5.mdl", "episodic" },
		{ "models/gibs/metal_gib5.phy", "episodic" },
		{ "models/gibs/metal_gib5.sw.vtx", "episodic" },
		{ "models/gibs/metal_gib5.vvd", "episodic" },
		{ "models/gibs/scanner_gib01.dx80.vtx", "episodic" },
		{ "models/gibs/scanner_gib01.dx90.vtx", "episodic" },
		{ "models/gibs/scanner_gib01.mdl", "episodic" },
		{ "models/gibs/scanner_gib01.phy", "episodic" },
		{ "models/gibs/scanner_gib01.sw.vtx", "episodic" },
		{ "models/gibs/scanner_gib01.vvd", "episodic" },
		{ "models/gibs/scanner_gib02.dx80.vtx", "episodic" },
		{ "models/gibs/scanner_gib02.dx90.vtx", "episodic" },
		{ "models/gibs/scanner_gib02.mdl", "episodic" },
		{ "models/gibs/scanner_gib02.phy", "episodic" },
		{ "models/gibs/scanner_gib02.sw.vtx", "episodic" },
		{ "models/gibs/scanner_gib02.vvd", "episodic" },
		{ "models/gibs/scanner_gib04.dx80.vtx", "episodic" },
		{ "models/gibs/scanner_gib04.dx90.vtx", "episodic" },
		{ "models/gibs/scanner_gib04.mdl", "episodic" },
		{ "models/gibs/scanner_gib04.phy", "episodic" },
		{ "models/gibs/scanner_gib04.sw.vtx", "episodic" },
		{ "models/gibs/scanner_gib04.vvd", "episodic" },
		{ "models/gibs/scanner_gib05.dx80.vtx", "episodic" },
		{ "models/gibs/scanner_gib05.dx90.vtx", "episodic" },
		{ "models/gibs/scanner_gib05.mdl", "episodic" },
		{ "models/gibs/scanner_gib05.phy", "episodic" },
		{ "models/gibs/scanner_gib05.sw.vtx", "episodic" },
		{ "models/gibs/scanner_gib05.vvd", "episodic" },
		{ "models/items/ammocrate_rockets.dx80.vtx", "episodic" },
		{ "models/items/ammocrate_rockets.dx90.vtx", "episodic" },
		{ "models/items/ammocrate_rockets.mdl", "episodic" },
		{ "models/items/ammocrate_rockets.phy", "episodic" },
		{ "models/items/ammocrate_rockets.sw.vtx", "episodic" },
		{ "models/items/ammocrate_rockets.vvd", "episodic" },
		{ "models/props_c17/canister_propane01a.dx80.vtx", "episodic" },
		{ "models/props_c17/canister_propane01a.dx90.vtx", "episodic" },
		{ "models/props_c17/canister_propane01a.mdl", "episodic" },
		{ "models/props_c17/canister_propane01a.phy", "episodic" },
		{ "models/props_c17/canister_propane01a.sw.vtx", "episodic" },
		{ "models/props_c17/canister_propane01a.vvd", "episodic" },
		{ "models/props_c17/chair_stool01a.dx80.vtx", "episodic" },
		{ "models/props_c17/chair_stool01a.dx90.vtx", "episodic" },
		{ "models/props_c17/chair_stool01a.mdl", "episodic" },
		{ "models/props_c17/chair_stool01a.phy", "episodic" },
		{ "models/props_c17/chair_stool01a.sw.vtx", "episodic" },
		{ "models/props_c17/chair_stool01a.vvd", "episodic" },
		{ "models/props_c17/clock01.dx80.vtx", "episodic" },
		{ "models/props_c17/clock01.dx90.vtx", "episodic" },
		{ "models/props_c17/clock01.mdl", "episodic" },
		{ "models/props_c17/clock01.phy", "episodic" },
		{ "models/props_c17/clock01.sw.vtx", "episodic" },
		{ "models/props_c17/clock01.vvd", "episodic" },
		{ "models/props_c17/display_cooler01a.dx80.vtx", "episodic" },
		{ "models/props_c17/display_cooler01a.dx90.vtx", "episodic" },
		{ "models/props_c17/display_cooler01a.mdl", "episodic" },
		{ "models/props_c17/display_cooler01a.phy", "episodic" },
		{ "models/props_c17/display_cooler01a.sw.vtx", "episodic" },
		{ "models/props_c17/display_cooler01a.vvd", "episodic" },
		{ "models/props_c17/door01_left.dx80.vtx", "episodic" },
		{ "models/props_c17/door01_left.dx90.vtx", "episodic" },
		{ "models/props_c17/door01_left.mdl", "episodic" },
		{ "models/props_c17/door01_left.phy", "episodic" },
		{ "models/props_c17/door01_left.sw.vtx", "episodic" },
		{ "models/props_c17/door01_left.vvd", "episodic" },
		{ "models/props_c17/door03_left.dx80.vtx", "episodic" },
		{ "models/props_c17/door03_left.dx90.vtx", "episodic" },
		{ "models/props_c17/door03_left.mdl", "episodic" },
		{ "models/props_c17/door03_left.phy", "episodic" },
		{ "models/props_c17/door03_left.sw.vtx", "episodic" },
		{ "models/props_c17/door03_left.vvd", "episodic" },
		{ "models/props_c17/furnitureshelf002a.dx80.vtx", "episodic" },
		{ "models/props_c17/furnitureshelf002a.dx90.vtx", "episodic" },
		{ "models/props_c17/furnitureshelf002a.mdl", "episodic" },
		{ "models/props_c17/furnitureshelf002a.phy", "episodic" },
		{ "models/props_c17/furnitureshelf002a.sw.vtx", "episodic" },
		{ "models/props_c17/furnitureshelf002a.vvd", "episodic" },
		{ "models/props_c17/hospital_bed01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_bed01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_bed01.mdl", "episodic" },
		{ "models/props_c17/hospital_bed01.phy", "episodic" },
		{ "models/props_c17/hospital_bed01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_bed01.vvd", "episodic" },
		{ "models/props_c17/hospital_cart01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_cart01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_cart01.mdl", "episodic" },
		{ "models/props_c17/hospital_cart01.phy", "episodic" },
		{ "models/props_c17/hospital_cart01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_cart01.vvd", "episodic" },
		{ "models/props_c17/hospital_ivstand01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_ivstand01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_ivstand01.mdl", "episodic" },
		{ "models/props_c17/hospital_ivstand01.phy", "episodic" },
		{ "models/props_c17/hospital_ivstand01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_ivstand01.vvd", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.mdl", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.phy", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_160_01.vvd", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.mdl", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.phy", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_256_01.vvd", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.mdl", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.phy", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_32_01.vvd", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.mdl", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.phy", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_railing_64_01.vvd", "episodic" },
		{ "models/props_c17/hospital_shelf01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_shelf01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_shelf01.mdl", "episodic" },
		{ "models/props_c17/hospital_shelf01.phy", "episodic" },
		{ "models/props_c17/hospital_shelf01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_shelf01.vvd", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.mdl", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.phy", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerylight01.vvd", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.dx80.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.dx90.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.mdl", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.phy", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.sw.vtx", "episodic" },
		{ "models/props_c17/hospital_surgerytable01.vvd", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.dx80.vtx", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.dx90.vtx", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.mdl", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.phy", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.sw.vtx", "episodic" },
		{ "models/props_c17/light_industrialbell01_on.vvd", "episodic" },
		{ "models/props_c17/lockers001a.dx80.vtx", "episodic" },
		{ "models/props_c17/lockers001a.dx90.vtx", "episodic" },
		{ "models/props_c17/lockers001a.mdl", "episodic" },
		{ "models/props_c17/lockers001a.phy", "episodic" },
		{ "models/props_c17/lockers001a.sw.vtx", "episodic" },
		{ "models/props_c17/lockers001a.vvd", "episodic" },
		{ "models/props_c17/metalladder004.dx80.vtx", "episodic" },
		{ "models/props_c17/metalladder004.dx90.vtx", "episodic" },
		{ "models/props_c17/metalladder004.mdl", "episodic" },
		{ "models/props_c17/metalladder004.phy", "episodic" },
		{ "models/props_c17/metalladder004.sw.vtx", "episodic" },
		{ "models/props_c17/metalladder004.vvd", "episodic" },
		{ "models/props_c17/metalladder005.dx80.vtx", "episodic" },
		{ "models/props_c17/metalladder005.dx90.vtx", "episodic" },
		{ "models/props_c17/metalladder005.mdl", "episodic" },
		{ "models/props_c17/metalladder005.phy", "episodic" },
		{ "models/props_c17/metalladder005.sw.vtx", "episodic" },
		{ "models/props_c17/metalladder005.vvd", "episodic" },
		{ "models/props_c17/pillarcluster_001b.dx80.vtx", "episodic" },
		{ "models/props_c17/pillarcluster_001b.dx90.vtx", "episodic" },
		{ "models/props_c17/pillarcluster_001b.mdl", "episodic" },
		{ "models/props_c17/pillarcluster_001b.phy", "episodic" },
		{ "models/props_c17/pillarcluster_001b.sw.vtx", "episodic" },
		{ "models/props_c17/pillarcluster_001b.vvd", "episodic" },
		{ "models/props_c17/powerbox.dx80.vtx", "episodic" },
		{ "models/props_c17/powerbox.dx90.vtx", "episodic" },
		{ "models/props_c17/powerbox.mdl", "episodic" },
		{ "models/props_c17/powerbox.phy", "episodic" },
		{ "models/props_c17/powerbox.sw.vtx", "episodic" },
		{ "models/props_c17/powerbox.vvd", "episodic" },
		{ "models/props_c17/slidinggate001.dx80.vtx", "episodic" },
		{ "models/props_c17/slidinggate001.dx90.vtx", "episodic" },
		{ "models/props_c17/slidinggate001.mdl", "episodic" },
		{ "models/props_c17/slidinggate001.phy", "episodic" },
		{ "models/props_c17/slidinggate001.sw.vtx", "episodic" },
		{ "models/props_c17/slidinggate001.vvd", "episodic" },
		{ "models/props_c17/undergroundelevator.dx80.vtx", "episodic" },
		{ "models/props_c17/undergroundelevator.dx90.vtx", "episodic" },
		{ "models/props_c17/undergroundelevator.mdl", "episodic" },
		{ "models/props_c17/undergroundelevator.sw.vtx", "episodic" },
		{ "models/props_c17/undergroundelevator.vvd", "episodic" },
		{ "models/props_combine/advisorpod_docked.dx80.vtx", "episodic" },
		{ "models/props_combine/advisorpod_docked.dx90.vtx", "episodic" },
		{ "models/props_combine/advisorpod_docked.mdl", "episodic" },
		{ "models/props_combine/advisorpod_docked.sw.vtx", "episodic" },
		{ "models/props_combine/advisorpod_docked.vvd", "episodic" },
		{ "models/props_combine/breenconsole.dx80.vtx", "episodic" },
		{ "models/props_combine/breenconsole.dx90.vtx", "episodic" },
		{ "models/props_combine/breenconsole.mdl", "episodic" },
		{ "models/props_combine/breenconsole.phy", "episodic" },
		{ "models/props_combine/breenconsole.sw.vtx", "episodic" },
		{ "models/props_combine/breenconsole.vvd", "episodic" },
		{ "models/props_combine/bunker_gun01.dx80.vtx", "episodic" },
		{ "models/props_combine/bunker_gun01.dx90.vtx", "episodic" },
		{ "models/props_combine/bunker_gun01.mdl", "episodic" },
		{ "models/props_combine/bunker_gun01.phy", "episodic" },
		{ "models/props_combine/bunker_gun01.sw.vtx", "episodic" },
		{ "models/props_combine/bunker_gun01.vvd", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.mdl", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.phy", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.sw.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_001a.vvd", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.dx80.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.dx90.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.mdl", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.phy", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.sw.vtx", "episodic" },
		{ "models/props_combine/combineinnerwallcluster1024_002a.vvd", "episodic" },
		{ "models/props_combine/combinewallcrushed.dx80.vtx", "episodic" },
		{ "models/props_combine/combinewallcrushed.dx90.vtx", "episodic" },
		{ "models/props_combine/combinewallcrushed.mdl", "episodic" },
		{ "models/props_combine/combinewallcrushed.phy", "episodic" },
		{ "models/props_combine/combinewallcrushed.sw.vtx", "episodic" },
		{ "models/props_combine/combinewallcrushed.vvd", "episodic" },
		{ "models/props_combine/combine_ballsocket.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_ballsocket.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_ballsocket.mdl", "episodic" },
		{ "models/props_combine/combine_ballsocket.phy", "episodic" },
		{ "models/props_combine/combine_ballsocket.sw.vtx", "episodic" },
		{ "models/props_combine/combine_ballsocket.vvd", "episodic" },
		{ "models/props_combine/combine_bridge_b01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_bridge_b01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_bridge_b01.mdl", "episodic" },
		{ "models/props_combine/combine_bridge_b01.phy", "episodic" },
		{ "models/props_combine/combine_bridge_b01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_bridge_b01.vvd", "episodic" },
		{ "models/props_combine/combine_citadel001.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadel001.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadel001.mdl", "episodic" },
		{ "models/props_combine/combine_citadel001.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadel001.vvd", "episodic" },
		{ "models/props_combine/combine_citadelbeacon.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelbeacon.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelbeacon.mdl", "episodic" },
		{ "models/props_combine/combine_citadelbeacon.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelbeacon.vvd", "episodic" },
		{ "models/props_combine/combine_citadelburst.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelburst.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelburst.mdl", "episodic" },
		{ "models/props_combine/combine_citadelburst.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelburst.vvd", "episodic" },
		{ "models/props_combine/combine_citadelcard001b.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcard001b.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcard001b.mdl", "episodic" },
		{ "models/props_combine/combine_citadelcard001b.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcard001b.vvd", "episodic" },
		{ "models/props_combine/combine_citadelcloud001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud001a.mdl", "episodic" },
		{ "models/props_combine/combine_citadelcloud001a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud001a.vvd", "episodic" },
		{ "models/props_combine/combine_citadelcloud002a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud002a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud002a.mdl", "episodic" },
		{ "models/props_combine/combine_citadelcloud002a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloud002a.vvd", "episodic" },
		{ "models/props_combine/combine_citadelcloudlight001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloudlight001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloudlight001a.mdl", "episodic" },
		{ "models/props_combine/combine_citadelcloudlight001a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelcloudlight001a.vvd", "episodic" },
		{ "models/props_combine/combine_citadeldestroyed001.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadeldestroyed001.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadeldestroyed001.mdl", "episodic" },
		{ "models/props_combine/combine_citadeldestroyed001.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadeldestroyed001.vvd", "episodic" },
		{ "models/props_combine/combine_citadelsplode001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelsplode001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelsplode001a.mdl", "episodic" },
		{ "models/props_combine/combine_citadelsplode001a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelsplode001a.vvd", "episodic" },
		{ "models/props_combine/combine_citadeltwirl.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadeltwirl.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadeltwirl.mdl", "episodic" },
		{ "models/props_combine/combine_citadeltwirl.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadeltwirl.vvd", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.mdl", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.phy", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed01.vvd", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.mdl", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.phy", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed02.vvd", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.mdl", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.phy", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.sw.vtx", "episodic" },
		{ "models/props_combine/combine_citadelwall_destroyed03.vvd", "episodic" },
		{ "models/props_combine/combine_core_arm01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_core_arm01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_core_arm01.mdl", "episodic" },
		{ "models/props_combine/combine_core_arm01.phy", "episodic" },
		{ "models/props_combine/combine_core_arm01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_core_arm01.vvd", "episodic" },
		{ "models/props_combine/combine_core_platform01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_core_platform01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_core_platform01.mdl", "episodic" },
		{ "models/props_combine/combine_core_platform01.phy", "episodic" },
		{ "models/props_combine/combine_core_platform01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_core_platform01.vvd", "episodic" },
		{ "models/props_combine/combine_core_ring01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_core_ring01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_core_ring01.mdl", "episodic" },
		{ "models/props_combine/combine_core_ring01.phy", "episodic" },
		{ "models/props_combine/combine_core_ring01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_core_ring01.vvd", "episodic" },
		{ "models/props_combine/combine_core_tube01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_core_tube01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_core_tube01.mdl", "episodic" },
		{ "models/props_combine/combine_core_tube01.phy", "episodic" },
		{ "models/props_combine/combine_core_tube01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_core_tube01.vvd", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.mdl", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.phy", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_debris128pile001a.vvd", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.mdl", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.phy", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_debris256barricade001a.vvd", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.mdl", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.phy", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_destroyedpipes01.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard01.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard02.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling01a_shard03.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_ceiling02a_shard01.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover01a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover02a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_cover03a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor01a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_floor02a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard01b.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard02b.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_shard03a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard01.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall01a_shard02.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard01.vvd", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.mdl", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.phy", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.sw.vtx", "episodic" },
		{ "models/props_combine/combine_explosivepanel_wall02a_shard02.vvd", "episodic" },
		{ "models/props_combine/combine_hatch01.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_hatch01.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_hatch01.mdl", "episodic" },
		{ "models/props_combine/combine_hatch01.phy", "episodic" },
		{ "models/props_combine/combine_hatch01.sw.vtx", "episodic" },
		{ "models/props_combine/combine_hatch01.vvd", "episodic" },
		{ "models/props_combine/combine_intmonitor001.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor001.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor001.mdl", "episodic" },
		{ "models/props_combine/combine_intmonitor001.phy", "episodic" },
		{ "models/props_combine/combine_intmonitor001.sw.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor001.vvd", "episodic" },
		{ "models/props_combine/combine_intmonitor003.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor003.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor003.mdl", "episodic" },
		{ "models/props_combine/combine_intmonitor003.phy", "episodic" },
		{ "models/props_combine/combine_intmonitor003.sw.vtx", "episodic" },
		{ "models/props_combine/combine_intmonitor003.vvd", "episodic" },
		{ "models/props_combine/combine_lightning001b.dx80.vtx", "episodic" },
		{ "models/props_combine/combine_lightning001b.dx90.vtx", "episodic" },
		{ "models/props_combine/combine_lightning001b.mdl", "episodic" },
		{ "models/props_combine/combine_lightning001b.sw.vtx", "episodic" },
		{ "models/props_combine/combine_lightning001b.vvd", "episodic" },
		{ "models/props_combine/coreball.dx80.vtx", "episodic" },
		{ "models/props_combine/coreball.dx90.vtx", "episodic" },
		{ "models/props_combine/coreball.mdl", "episodic" },
		{ "models/props_combine/coreball.phy", "episodic" },
		{ "models/props_combine/coreball.sw.vtx", "episodic" },
		{ "models/props_combine/coreball.vvd", "episodic" },
		{ "models/props_combine/corecontrolmonitor.dx80.vtx", "episodic" },
		{ "models/props_combine/corecontrolmonitor.dx90.vtx", "episodic" },
		{ "models/props_combine/corecontrolmonitor.mdl", "episodic" },
		{ "models/props_combine/corecontrolmonitor.sw.vtx", "episodic" },
		{ "models/props_combine/corecontrolmonitor.vvd", "episodic" },
		{ "models/props_combine/corecontrol_set001.dx80.vtx", "episodic" },
		{ "models/props_combine/corecontrol_set001.dx90.vtx", "episodic" },
		{ "models/props_combine/corecontrol_set001.mdl", "episodic" },
		{ "models/props_combine/corecontrol_set001.phy", "episodic" },
		{ "models/props_combine/corecontrol_set001.sw.vtx", "episodic" },
		{ "models/props_combine/corecontrol_set001.vvd", "episodic" },
		{ "models/props_combine/soldier_bed.dx80.vtx", "episodic" },
		{ "models/props_combine/soldier_bed.dx90.vtx", "episodic" },
		{ "models/props_combine/soldier_bed.mdl", "episodic" },
		{ "models/props_combine/soldier_bed.phy", "episodic" },
		{ "models/props_combine/soldier_bed.sw.vtx", "episodic" },
		{ "models/props_combine/soldier_bed.vvd", "episodic" },
		{ "models/props_combine/stalkercar.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkercar.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkercar.mdl", "episodic" },
		{ "models/props_combine/stalkercar.sw.vtx", "episodic" },
		{ "models/props_combine/stalkercar.vvd", "episodic" },
		{ "models/props_combine/stalkerpod.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod.mdl", "episodic" },
		{ "models/props_combine/stalkerpod.phy", "episodic" },
		{ "models/props_combine/stalkerpod.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod.vvd", "episodic" },
		{ "models/props_combine/stalkerpod_legs.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_legs.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_legs.mdl", "episodic" },
		{ "models/props_combine/stalkerpod_legs.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_legs.vvd", "episodic" },
		{ "models/props_combine/stalkerpod_lid.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_lid.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_lid.mdl", "episodic" },
		{ "models/props_combine/stalkerpod_lid.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_lid.vvd", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.mdl", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.phy", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_nolid.vvd", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.mdl", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.phy", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_physanim.vvd", "episodic" },
		{ "models/props_combine/stalkerpod_torso.ani", "episodic" },
		{ "models/props_combine/stalkerpod_torso.dx80.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_torso.dx90.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_torso.mdl", "episodic" },
		{ "models/props_combine/stalkerpod_torso.sw.vtx", "episodic" },
		{ "models/props_combine/stalkerpod_torso.vvd", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.mdl", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.phy", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_section128floor001b.vvd", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.mdl", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.phy", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001a.vvd", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.mdl", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.phy", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001b.vvd", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.mdl", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.phy", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_section64floor001c.vvd", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.mdl", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.phy", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001a.vvd", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.mdl", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.phy", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001b.vvd", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.mdl", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.phy", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001c.vvd", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.dx80.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.dx90.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.mdl", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.phy", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.sw.vtx", "episodic" },
		{ "models/props_debris/concrete_spawnchunk001d.vvd", "episodic" },
		{ "models/props_debris/dog_introrocks.dx80.vtx", "episodic" },
		{ "models/props_debris/dog_introrocks.dx90.vtx", "episodic" },
		{ "models/props_debris/dog_introrocks.mdl", "episodic" },
		{ "models/props_debris/dog_introrocks.sw.vtx", "episodic" },
		{ "models/props_debris/dog_introrocks.vvd", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.dx80.vtx", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.dx90.vtx", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.mdl", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.phy", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.sw.vtx", "episodic" },
		{ "models/props_debris/metal_panel01a_breakable.vvd", "episodic" },
		{ "models/props_debris/rebar002a_32.dx80.vtx", "episodic" },
		{ "models/props_debris/rebar002a_32.dx90.vtx", "episodic" },
		{ "models/props_debris/rebar002a_32.mdl", "episodic" },
		{ "models/props_debris/rebar002a_32.phy", "episodic" },
		{ "models/props_debris/rebar002a_32.sw.vtx", "episodic" },
		{ "models/props_debris/rebar002a_32.vvd", "episodic" },
		{ "models/props_debris/rebar002c_64.dx80.vtx", "episodic" },
		{ "models/props_debris/rebar002c_64.dx90.vtx", "episodic" },
		{ "models/props_debris/rebar002c_64.mdl", "episodic" },
		{ "models/props_debris/rebar002c_64.phy", "episodic" },
		{ "models/props_debris/rebar002c_64.sw.vtx", "episodic" },
		{ "models/props_debris/rebar002c_64.vvd", "episodic" },
		{ "models/props_debris/rebar003a_32.dx80.vtx", "episodic" },
		{ "models/props_debris/rebar003a_32.dx90.vtx", "episodic" },
		{ "models/props_debris/rebar003a_32.mdl", "episodic" },
		{ "models/props_debris/rebar003a_32.phy", "episodic" },
		{ "models/props_debris/rebar003a_32.sw.vtx", "episodic" },
		{ "models/props_debris/rebar003a_32.vvd", "episodic" },
		{ "models/props_debris/walldestroyed02a.dx80.vtx", "episodic" },
		{ "models/props_debris/walldestroyed02a.dx90.vtx", "episodic" },
		{ "models/props_debris/walldestroyed02a.mdl", "episodic" },
		{ "models/props_debris/walldestroyed02a.phy", "episodic" },
		{ "models/props_debris/walldestroyed02a.sw.vtx", "episodic" },
		{ "models/props_debris/walldestroyed02a.vvd", "episodic" },
		{ "models/props_debris/walldestroyed09a.dx80.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09a.dx90.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09a.mdl", "episodic" },
		{ "models/props_debris/walldestroyed09a.phy", "episodic" },
		{ "models/props_debris/walldestroyed09a.sw.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09a.vvd", "episodic" },
		{ "models/props_debris/walldestroyed09f.dx80.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09f.dx90.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09f.mdl", "episodic" },
		{ "models/props_debris/walldestroyed09f.phy", "episodic" },
		{ "models/props_debris/walldestroyed09f.sw.vtx", "episodic" },
		{ "models/props_debris/walldestroyed09f.vvd", "episodic" },
		{ "models/props_doors/door03_slotted_left.dx80.vtx", "episodic" },
		{ "models/props_doors/door03_slotted_left.dx90.vtx", "episodic" },
		{ "models/props_doors/door03_slotted_left.mdl", "episodic" },
		{ "models/props_doors/door03_slotted_left.phy", "episodic" },
		{ "models/props_doors/door03_slotted_left.sw.vtx", "episodic" },
		{ "models/props_doors/door03_slotted_left.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_01.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_01.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_01.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_01.phy", "episodic" },
		{ "models/props_foliage/tree_pine_01.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_01.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_02.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_02.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_02.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_02.phy", "episodic" },
		{ "models/props_foliage/tree_pine_02.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_02.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_03.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_03.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_03.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_03.phy", "episodic" },
		{ "models/props_foliage/tree_pine_03.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_03.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_01.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_01.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_01.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_01.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_01.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02_skybox.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02_skybox.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02_skybox.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02_skybox.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_card_cluster_02_skybox.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.phy", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_cluster_01.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_tall_01.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_01.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_01.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_tall_01.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_01.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_tall_02.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_02.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_02.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_tall_02.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_02.vvd", "episodic" },
		{ "models/props_foliage/tree_pine_tall_cluster_01.dx80.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_cluster_01.dx90.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_cluster_01.mdl", "episodic" },
		{ "models/props_foliage/tree_pine_tall_cluster_01.sw.vtx", "episodic" },
		{ "models/props_foliage/tree_pine_tall_cluster_01.vvd", "episodic" },
		{ "models/props_interiors/lightsconce01.dx80.vtx", "episodic" },
		{ "models/props_interiors/lightsconce01.dx90.vtx", "episodic" },
		{ "models/props_interiors/lightsconce01.mdl", "episodic" },
		{ "models/props_interiors/lightsconce01.phy", "episodic" },
		{ "models/props_interiors/lightsconce01.sw.vtx", "episodic" },
		{ "models/props_interiors/lightsconce01.vvd", "episodic" },
		{ "models/props_junk/bicycle01a.dx80.vtx", "episodic" },
		{ "models/props_junk/bicycle01a.dx90.vtx", "episodic" },
		{ "models/props_junk/bicycle01a.mdl", "episodic" },
		{ "models/props_junk/bicycle01a.phy", "episodic" },
		{ "models/props_junk/bicycle01a.sw.vtx", "episodic" },
		{ "models/props_junk/bicycle01a.vvd", "episodic" },
		{ "models/props_junk/flare.dx80.vtx", "episodic" },
		{ "models/props_junk/flare.dx90.vtx", "episodic" },
		{ "models/props_junk/flare.mdl", "episodic" },
		{ "models/props_junk/flare.phy", "episodic" },
		{ "models/props_junk/flare.sw.vtx", "episodic" },
		{ "models/props_junk/flare.vvd", "episodic" },
		{ "models/props_junk/propane_tank001a.dx80.vtx", "episodic" },
		{ "models/props_junk/propane_tank001a.dx90.vtx", "episodic" },
		{ "models/props_junk/propane_tank001a.mdl", "episodic" },
		{ "models/props_junk/propane_tank001a.phy", "episodic" },
		{ "models/props_junk/propane_tank001a.sw.vtx", "episodic" },
		{ "models/props_junk/propane_tank001a.vvd", "episodic" },
		{ "models/props_junk/vent001.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001.mdl", "episodic" },
		{ "models/props_junk/vent001.phy", "episodic" },
		{ "models/props_junk/vent001.sw.vtx", "episodic" },
		{ "models/props_junk/vent001.vvd", "episodic" },
		{ "models/props_junk/vent001_chunk1.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk1.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk1.mdl", "episodic" },
		{ "models/props_junk/vent001_chunk1.phy", "episodic" },
		{ "models/props_junk/vent001_chunk1.sw.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk1.vvd", "episodic" },
		{ "models/props_junk/vent001_chunk4.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk4.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk4.mdl", "episodic" },
		{ "models/props_junk/vent001_chunk4.phy", "episodic" },
		{ "models/props_junk/vent001_chunk4.sw.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk4.vvd", "episodic" },
		{ "models/props_junk/vent001_chunk6.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk6.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk6.mdl", "episodic" },
		{ "models/props_junk/vent001_chunk6.phy", "episodic" },
		{ "models/props_junk/vent001_chunk6.sw.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk6.vvd", "episodic" },
		{ "models/props_junk/vent001_chunk7.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk7.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk7.mdl", "episodic" },
		{ "models/props_junk/vent001_chunk7.phy", "episodic" },
		{ "models/props_junk/vent001_chunk7.sw.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk7.vvd", "episodic" },
		{ "models/props_junk/vent001_chunk8.dx80.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk8.dx90.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk8.mdl", "episodic" },
		{ "models/props_junk/vent001_chunk8.phy", "episodic" },
		{ "models/props_junk/vent001_chunk8.sw.vtx", "episodic" },
		{ "models/props_junk/vent001_chunk8.vvd", "episodic" },
		{ "models/props_lab/mobileprojector.dx80.vtx", "episodic" },
		{ "models/props_lab/mobileprojector.dx90.vtx", "episodic" },
		{ "models/props_lab/mobileprojector.mdl", "episodic" },
		{ "models/props_lab/mobileprojector.phy", "episodic" },
		{ "models/props_lab/mobileprojector.sw.vtx", "episodic" },
		{ "models/props_lab/mobileprojector.vvd", "episodic" },
		{ "models/props_lab/mobileprojector_beam.dx80.vtx", "episodic" },
		{ "models/props_lab/mobileprojector_beam.dx90.vtx", "episodic" },
		{ "models/props_lab/mobileprojector_beam.mdl", "episodic" },
		{ "models/props_lab/mobileprojector_beam.sw.vtx", "episodic" },
		{ "models/props_lab/mobileprojector_beam.vvd", "episodic" },
		{ "models/props_lab/monitor02.dx80.vtx", "episodic" },
		{ "models/props_lab/monitor02.dx90.vtx", "episodic" },
		{ "models/props_lab/monitor02.mdl", "episodic" },
		{ "models/props_lab/monitor02.phy", "episodic" },
		{ "models/props_lab/monitor02.sw.vtx", "episodic" },
		{ "models/props_lab/monitor02.vvd", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.dx80.vtx", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.dx90.vtx", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.mdl", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.phy", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.sw.vtx", "episodic" },
		{ "models/props_lab/scrapyarddumpster_static.vvd", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.dx80.vtx", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.dx90.vtx", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.mdl", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.phy", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.sw.vtx", "episodic" },
		{ "models/props_outland/pumpkin01_explosive.vvd", "episodic" },
		{ "models/props_rooftop/attic_window.dx80.vtx", "episodic" },
		{ "models/props_rooftop/attic_window.dx90.vtx", "episodic" },
		{ "models/props_rooftop/attic_window.mdl", "episodic" },
		{ "models/props_rooftop/attic_window.phy", "episodic" },
		{ "models/props_rooftop/attic_window.sw.vtx", "episodic" },
		{ "models/props_rooftop/attic_window.vvd", "episodic" },
		{ "models/props_trainstation/train001.dx80.vtx", "episodic" },
		{ "models/props_trainstation/train001.dx90.vtx", "episodic" },
		{ "models/props_trainstation/train001.mdl", "episodic" },
		{ "models/props_trainstation/train001.phy", "episodic" },
		{ "models/props_trainstation/train001.sw.vtx", "episodic" },
		{ "models/props_trainstation/train001.vvd", "episodic" },
		{ "models/props_trainstation/train_outro_car01.dx80.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_car01.dx90.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_car01.mdl", "episodic" },
		{ "models/props_trainstation/train_outro_car01.phy", "episodic" },
		{ "models/props_trainstation/train_outro_car01.sw.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_car01.vvd", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.dx80.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.dx90.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.mdl", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.phy", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.sw.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch01.vvd", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.dx80.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.dx90.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.mdl", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.phy", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.sw.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch02.vvd", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.dx80.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.dx90.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.mdl", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.phy", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.sw.vtx", "episodic" },
		{ "models/props_trainstation/train_outro_porch03.vvd", "episodic" },
		{ "models/props_wasteland/interior_fence002d.dx80.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence002d.dx90.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence002d.mdl", "episodic" },
		{ "models/props_wasteland/interior_fence002d.phy", "episodic" },
		{ "models/props_wasteland/interior_fence002d.sw.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence002d.vvd", "episodic" },
		{ "models/props_wasteland/interior_fence004b.dx80.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence004b.dx90.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence004b.mdl", "episodic" },
		{ "models/props_wasteland/interior_fence004b.phy", "episodic" },
		{ "models/props_wasteland/interior_fence004b.sw.vtx", "episodic" },
		{ "models/props_wasteland/interior_fence004b.vvd", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.dx80.vtx", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.dx90.vtx", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.mdl", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.phy", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.sw.vtx", "episodic" },
		{ "models/vehicles/vehicle_blackout_e1_dogintro.vvd", "episodic" },
		{ "models/vehicles/vehicle_van.dx80.vtx", "episodic" },
		{ "models/vehicles/vehicle_van.dx90.vtx", "episodic" },
		{ "models/vehicles/vehicle_van.mdl", "episodic" },
		{ "models/vehicles/vehicle_van.phy", "episodic" },
		{ "models/vehicles/vehicle_van.sw.vtx", "episodic" },
		{ "models/vehicles/vehicle_van.vvd", "episodic" },
		{ "models/vehicles/vehicle_vandoor.dx80.vtx", "episodic" },
		{ "models/vehicles/vehicle_vandoor.dx90.vtx", "episodic" },
		{ "models/vehicles/vehicle_vandoor.mdl", "episodic" },
		{ "models/vehicles/vehicle_vandoor.phy", "episodic" },
		{ "models/vehicles/vehicle_vandoor.sw.vtx", "episodic" },
		{ "models/vehicles/vehicle_vandoor.vvd", "episodic" },
		{ "models/weapons/w_alyx_gun.dx80.vtx", "episodic" },
		{ "models/weapons/w_alyx_gun.dx90.vtx", "episodic" },
		{ "models/weapons/w_alyx_gun.mdl", "episodic" },
		{ "models/weapons/w_alyx_gun.phy", "episodic" },
		{ "models/weapons/w_alyx_gun.sw.vtx", "episodic" },
		{ "models/weapons/w_alyx_gun.vvd", "episodic" },
		{ "models/zombie/classic.ani", "episodic" },
		{ "models/zombie/classic.dx80.vtx", "episodic" },
		{ "models/zombie/classic.dx90.vtx", "episodic" },
		{ "models/zombie/classic.mdl", "episodic" },
		{ "models/zombie/classic.phy", "episodic" },
		{ "models/zombie/classic.sw.vtx", "episodic" },
		{ "models/zombie/classic.vvd", "episodic" },
		{ "models/zombie/classic_torso.ani", "episodic" },
		{ "models/zombie/classic_torso.dx80.vtx", "episodic" },
		{ "models/zombie/classic_torso.dx90.vtx", "episodic" },
		{ "models/zombie/classic_torso.mdl", "episodic" },
		{ "models/zombie/classic_torso.phy", "episodic" },
		{ "models/zombie/classic_torso.sw.vtx", "episodic" },
		{ "models/zombie/classic_torso.vvd", "episodic" },
		{ "models/zombie/fast.ani", "episodic" },
		{ "models/zombie/fast.dx80.vtx", "episodic" },
		{ "models/zombie/fast.dx90.vtx", "episodic" },
		{ "models/zombie/fast.mdl", "episodic" },
		{ "models/zombie/fast.phy", "episodic" },
		{ "models/zombie/fast.sw.vtx", "episodic" },
		{ "models/zombie/fast.vvd", "episodic" },
		{ "models/zombie/fast_torso.ani", "episodic" },
		{ "models/zombie/fast_torso.dx80.vtx", "episodic" },
		{ "models/zombie/fast_torso.dx90.vtx", "episodic" },
		{ "models/zombie/fast_torso.mdl", "episodic" },
		{ "models/zombie/fast_torso.phy", "episodic" },
		{ "models/zombie/fast_torso.sw.vtx", "episodic" },
		{ "models/zombie/fast_torso.vvd", "episodic" },
		{ "models/zombie/poison.ani", "episodic" },
		{ "models/zombie/poison.dx80.vtx", "episodic" },
		{ "models/zombie/poison.dx90.vtx", "episodic" },
		{ "models/zombie/poison.mdl", "episodic" },
		{ "models/zombie/poison.phy", "episodic" },
		{ "models/zombie/poison.sw.vtx", "episodic" },
		{ "models/zombie/poison.vvd", "episodic" },
		{ "models/zombie/zombie_soldier.dx80.vtx", "episodic" },
		{ "models/zombie/zombie_soldier.dx90.vtx", "episodic" },
		{ "models/zombie/zombie_soldier.mdl", "episodic" },
		{ "models/zombie/zombie_soldier.phy", "episodic" },
		{ "models/zombie/zombie_soldier.sw.vtx", "episodic" },
		{ "models/zombie/zombie_soldier.vvd", "episodic" },
		{ "models/zombie/zombie_soldier_animations.ani", "episodic" },
		{ "models/zombie/zombie_soldier_animations.mdl", "episodic" },
		{ "models/zombie/zombie_soldier_legs.dx80.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_legs.dx90.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_legs.mdl", "episodic" },
		{ "models/zombie/zombie_soldier_legs.phy", "episodic" },
		{ "models/zombie/zombie_soldier_legs.sw.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_legs.vvd", "episodic" },
		{ "models/zombie/zombie_soldier_torso.dx80.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_torso.dx90.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_torso.mdl", "episodic" },
		{ "models/zombie/zombie_soldier_torso.phy", "episodic" },
		{ "models/zombie/zombie_soldier_torso.sw.vtx", "episodic" },
		{ "models/zombie/zombie_soldier_torso.vvd", "episodic" },
	}

	GMA.CreatePackage(requiredFiles, "lambda_ep1_content.dat")

	PrintTable(game.MountGMA("data/lambda_ep1_content.dat"))

end

function GAMETYPE:GetPlayerLoadout()
	return self.MapScript.DefaultLoadout
end

hook.Add("LambdaLoadGameTypes", "HL2EP1GameType", function(gametypes)
	gametypes:Add("hl2ep1", GAMETYPE)
end)

if CLIENT then
	language.Add("episodic_Chapter1_Title", "Undue Alarm")
	language.Add("episodic_Chapter2_Title", "Direct Intervention")
	language.Add("episodic_Chapter4_Title", "Urban Flight")
	language.Add("episodic_Chapter3_Title", "Lowlife")
	language.Add("episodic_Chapter5_Title", "Exit 17")
	language.Add("episodic_Chapter6_Title", "Coming Soon")

	language.Add("mod_episodic_Chapter1_Title", "Undue Alarm")
	language.Add("mod_episodic_Chapter2_Title", "Direct Intervention")
	language.Add("mod_episodic_Chapter4_Title", "Urban Flight")
	language.Add("mod_episodic_Chapter3_Title", "Lowlife")
	language.Add("mod_episodic_Chapter5_Title", "Exit 17")
	language.Add("mod_episodic_Chapter6_Title", "Coming Soon")

	language.Add("halflife-vr-ep1_Chapter1_Title", "Undue Alarm")
	language.Add("halflife-vr-ep1_Chapter2_Title", "Direct Intervention")
	language.Add("halflife-vr-ep1_Chapter4_Title", "Urban Flight")
	language.Add("halflife-vr-ep1_Chapter3_Title", "Lowlife")
	language.Add("halflife-vr-ep1_Chapter5_Title", "Exit 17")
	language.Add("halflife-vr-ep1_Chapter6_Title", "Coming Soon")

	language.Add("HL2_GameOver_Object","IT ENDS HERE\nTHE FREEMAN HAS FAILED TO PRESERVE RESOURCES\nDEEMED CRITICAL TO VICTORY\nINESCAPABLE GLIMPSES OF DOOM CLOUD THE VORTESSENCE")
	language.Add("HL2_GameOver_Ally","SO IT ENDS\nTHE FREEMAN HAS FAILED TO PRESERVE A LIFE REQUIRED FOR VICTORY\nSUCH ARE THE SHAPES WE SEE IN THE VORTESSENCE")
	language.Add("HL2_GameOver_Timer","ALL IS DONE\nTHE FREEMAN'S FAILURE TO SEIZE A SWIFT VICTORY\nLEADS TO OUR TOTAL DEFEAT")
	language.Add("HL2_GameOver_Stuck","ASSIGNMENT: TERMINATED\nSUBJECT: FREEMAN\nREASON: DEMONSTRATION OF EXCEEDINGLY POOR JUDGMENT")
	language.Add("Episodic_GameOver_AlyxDead", "THE ALYX VANCE HAS DIED\nWITHOUT HER WE CANNOT PERSEVERE")

	language.Add("HL2_357Handgun", ".357 MAGNUM")
	language.Add("HL2_Pulse_Rifle", "OVERWATCH STANDARD ISSUE\n(PULSE-RIFLE)")
	language.Add("HL2_Bugbait", "PHEROPOD\n(BUGBAIT)")
	language.Add("HL2_Crossbow", "CROSSBOW")
	language.Add("HL2_Crowbar", "CROWBAR")
	language.Add("HL2_Grenade", "GRENADE")
	language.Add("HL2_GravityGun", "ZERO-POINT ENERGY GUN\n(GRAVITY GUN)")
	language.Add("HL2_Pistol", "9MM PISTOL")
	language.Add("HL2_RPG", "RPG\n(ROCKET PROPELLED GRENADE)")
	language.Add("HL2_Shotgun", "SHOTGUN")
	language.Add("HL2_SMG1", "SMG\n(SUBMACHINE GUN)")
	language.Add("HL2_Saved", "Saved...")
	language.Add("HL2_Enable_Commentary", "Enable commentary track")

	language.Add("Valve_Hint_EnterVan", "%+use% ENTER VAN")
	language.Add("Valve_Hint_ExitVan", "%+use% EXIT VAN")

	language.Add("Valve_Hint_Crouch", "%+duck% CROUCH")
	language.Add("Valve_Hint_Sprint", "%+speed% SPRINT")
	language.Add("Valve_Hint_PushButton", "%+use% PUSH BUTTON")
	language.Add("Valve_Hint_PicKUp", "%+use% PICK UP")
	language.Add("Valve_Hint_Interact", "%+use% INTERACT")
	language.Add("Valve_Hint_GravGun", "%+attack% PUNT OBJECT %+attack2% PULL OBJECT")
	language.Add("Valve_Hint_CarryTurret", "%+use% OR GRAVITY GUN TO PICK UP TURRET")
	language.Add("Valve_Hint_CROSSBOW", "%+attack2% CROSSBOW ZOOM")

	language.Add("HL2_Credits_VoicesTitle", "Voices:")
	language.Add("HL2_Credits_Eli","Robert Guillaume - Dr. Eli Vance")
	language.Add("HL2_Credits_Breen","Robert Culp - Dr. Wallace Breen")
	language.Add("HL2_Credits_Vortigaunt", "Lou Gossett, Jr. - Vortigaunt")
	language.Add("HL2_Credits_Mossman","Michelle Forbes - Dr. Judith Mossman")
	language.Add("HL2_Credits_Alyx","Merle Dandridge - Alyx Vance")
	language.Add("HL2_Credits_Barney","Mike Shapiro - Barney Calhoun")
	language.Add("HL2_Credits_Gman","Mike Shapiro - Gman")
	language.Add("HL2_Credits_Kleiner","Harry S. Robins - Dr. Isaac Kleiner")
	language.Add("HL2_Credits_Grigori","Jim French - Father Grigori")
	language.Add("HL2_Credits_Misc1", "John Patrick Lowrie - Citizens\nMisc. characters")
	language.Add("HL2_Credits_Misc2","Mary Kae Irvin - Citizens\nMisc. characters")
	language.Add("HL2_Credits_Overwatch","Ellen McLain - Overwatch")
	language.Add("HL2_Credits_VoiceCastingTitle", "Voice Casting:")
	language.Add("HL2_Credits_VoiceCastingText", "Shana Landsburg\nTeri Fiddleman")
	language.Add("HL2_Credits_VoiceRecordingTitle", "Voice Recording:")
	language.Add("HL2_Credits_VoiceRecordingText1", "Pure Audio, Seattle, WA")
	language.Add("HL2_Credits_VoiceRecordingText2", "LA Studios, LA, CA")
	language.Add("HL2_Credits_VoiceSchedulingTitle", "Voice recording scheduling and logistics:")
	language.Add("HL2_Credits_VoiceSchedulingText", "Pat Cockburn, Pure Audio")
	language.Add("HL2_Credits_LegalTeam","Crack Legal Team:")
	language.Add("HL2_Credits_FacesThanks", "Thanks to the following for the use of their faces:")
	language.Add("HL2_Credits_SpecialThanks", "Special thanks to everyone at:")

	language.Add("EP1_BEAT_MAINELEVATOR_NAME", "Watch Your Head!")
	language.Add("EP1_BEAT_MAINELEVATOR_DESC", "Make it to the bottom of the Citadel's main elevator shaft in one piece.")
	language.Add("EP1_BEAT_CITADELCORE_NAME", "Containment")
	language.Add("EP1_BEAT_CITADELCORE_DESC", "Contain the Citadel core.")
	language.Add("EP1_BEAT_CITADELCORE_NOSTALKERKILLS_NAME", "Pacifist")
	language.Add("EP1_BEAT_CITADELCORE_NOSTALKERKILLS_DESC", "Contain the Citadel core without killing any stalkers.")
	language.Add("EP1_KILL_ANTLIONS_WITHCARS_NAME", "Car Crusher")
	language.Add("EP1_KILL_ANTLIONS_WITHCARS_DESC", "Use the cars to squash 15 antlions in Episode One.")
	language.Add("EP1_BEAT_GARAGEELEVATORSTANDOFF_NAME", "Elevator Action")
	language.Add("EP1_BEAT_GARAGEELEVATORSTANDOFF_DESC", "Survive long enough to get on the parking garage elevator.")
	language.Add("EP1_KILL_ENEMIES_WITHSNIPERALYX_NAME", "Live Bait")
	language.Add("EP1_KILL_ENEMIES_WITHSNIPERALYX_DESC", "Help Alyx snipe 30 enemies in Episode One.")
	language.Add("EP1_BEAT_HOSPITALATTICGUNSHIP_NAME", "Attica!")
	language.Add("EP1_BEAT_HOSPITALATTICGUNSHIP_DESC", "Destroy the gunship in the hospital attic.")
	language.Add("EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_NAME", "Citizen Escort")
	language.Add("EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_DESC", "Don't let any citizens die when escorting them to the escape train.")
	language.Add("EP1_BEAT_GAME_NAME", "Escape From City 17")
	language.Add("EP1_BEAT_GAME_DESC", "Escape City 17 with Alyx.")
	language.Add("EP1_BEAT_GAME_ONEBULLET_NAME", "The One Free Bullet")
	language.Add("EP1_BEAT_GAME_ONEBULLET_DESC", "Finish the game firing exactly one bullet. Grenade, crowbar, rocket, and Gravity Gun kills are okay!")

	language.Add("World", "Cruel World")
	language.Add("base_ai", "Creature")
end
