name: Workshop Update - Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  Workshop-Publish-Test:
    uses: ./.github/workflows/WorkshopPublish.yml
    with:
      workshop-id: '801875828' # 780244493
    secrets: inherit