name: Workshop Update - Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  Workshop-Publish-Release:
    uses: ./.github/workflows/WorkshopPublish.yml
    with:
      workshop-id: '780244493'
    secrets: inherit